[font]
size = 10.0

## When true, Alacritty will use a custom built-in font for box drawing characters and p>
builtin_box_drawing = true

[font.normal]
##family = "Iosevka Nerd Font"
family = "JetBrains Mono"

#style = "Regular"

[font.bold]
##family = "Iosevka Nerd Font"
family = "JetBrains Mono"

[font.italic]
##family = "Iosevka Nerd Font"
##family = "JetBrainsMono Nerd Font"
family = "JetBrains Mono"

[font.bold_italic]
##family = "JetBrainsMono Nerd Font"
family = "JetBrains Mono"

## Offset is the extra space around each character.
## 'y' can be thought of as modifying the line spacing, and 'x' as modifying the letter >
[font.offset]
x = 1
y = 0

# Glyph offset determines the locations of the glyphs within their cells with the defau>
## Increasing 'x' moves the glyph to the right, increasing 'y' moves the glyph upward.
[font.glyph_offset]
x = 0
y = 0

